kind: Config
apiVersion: kind.sigs.k8s.io/v1alpha2
nodes:
  - role: control-plane
    kubeadmConfigPatchesJson6902:
      - group: kubeadm.k8s.io
        version: v1beta1
        kind: ClusterConfiguration
        patch: |
          - op: add
            path: /apiServer/certSANs/-
            value: host.docker.internal