
jobs:
  include:
    - stage: test
      language: go
      go:
        - 1.12.x
      env:
        - OS=linux KUBEBUILDER_VERSION=1.0.8
      before_script:
        - curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KUBEBUILDER_VERSION}/kubebuilder_${KUBEBUILDER_VERSION}_${OS}_amd64.tar.gz"
        - tar -zxvf kubebuilder_${KUBEBUILDER_VERSION}_${OS}_amd64.tar.gz
        - mv kubebuilder_${KUBEBUILDER_VERSION}_${OS}_amd64 kubebuilder && sudo mv kubebuilder /usr/local/
        - export PATH=$PATH:/usr/local/kubebuilder/bin
      script: make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build-images
      language: generic
      sudo: required
      before_script:
        - curl -L https://github.com/opctl/opctl/releases/download/0.1.24/opctl0.1.24.linux.tgz | sudo tar -xzv -C /usr/local/bin
      services:
        - docker
      script:
        - opctl run build
notifications:
  email: false
