apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: aksclusters.azure.cnct.io
spec:
  group: azure.cnct.io
  names:
    kind: AksCluster
    plural: aksclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            agentPoolProfiles:
              description: Agent Pool Profiles
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  name:
                    type: string
                  vmSize:
                    type: string
                type: object
              type: array
            credentials:
              description: Credentials used to access the azure environment (must
                have access to blob storageaccount)
              properties:
                loginId:
                  type: string
                loginSecret:
                  type: string
                subscriptionId:
                  type: string
                tenantId:
                  type: string
              type: object
            kubernetesVersion:
              description: Kubernetes version
              type: string
            location:
              description: Region where you are creating the cluster
              type: string
            masterProfile:
              description: Master Profile configuration
              properties:
                count:
                  format: int64
                  type: integer
                dnsPrefix:
                  type: string
                vmSize:
                  type: string
              type: object
          required:
          - kubernetesVersion
          - masterProfile
          type: object
        status:
          properties:
            phase:
              description: Cluster status
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
