---
apiVersion: v1
kind: Secret
metadata:
  name: akscluster-sample-secret
type: Opaque
data:
  tenantId:
  subscriptionId:
  loginId:
  loginSecret:
---
apiVersion: azure.cnct.io/v1beta1
kind: AksCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: akscluster-sample
spec:
  credentials: credentials-k8s-secret
  location: westus
  kubernetesVersion: "1.13"
  masterProfile:
    count: 1
    dnsPrefix: akscluster-sample
    vmSize: Standard_D2_v2
  agentPoolProfiles:
    - name: agentpool1
      count: 1
      vmSize: Standard_D2_v2
