---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-k8s-secret
type: Opaque
data:
  tenantId: <base64tenantId>
  subscriptionId: <base64subscriptionId>
  loginId: <base64loginId>
  loginSecret: <base64loginSecret>
---
apiVersion: azure.cnct.io/v1beta1
kind: AksCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-cluster
spec:
  credentials: credentials-k8s-secret
  location: westus
  kubernetesVersion: "1.13.5"
  masterProfile:
    count: 1
    dnsPrefix: sample-cluster
    vmSize: Standard_D2_v2
  agentPoolProfiles:
    - name: agentpool1
      count: 1
      vmSize: Standard_D2_v2
